# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: ~/symfony

    steps:
      - checkout
      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo apt install -y zlib1g-dev libicu-dev g++
            sudo docker-php-ext-install zip
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install intl
            sudo docker-php-ext-install pdo_mysql
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json"}}
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: composer install
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Create database and run migration"
          command: |

            php bin/console doctrine:database:create
            php bin/console doctrine:migrations:migrate
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit
