# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json"}}
            - v1-dependencies-
      - run:
          name: "Install Dependencies"
          command: composer install -n --prefix-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: "Create database and run migration"
          command: |
            php bin/console doctrine:migrations:migrate
      - run:
          name: "Run Tests"
          command: ./vendor/bin/phpunit
